### PR TITLE
Update semver dependency to 0.2

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
In Servo we like to avoid multiple versions of the same crate to manage growth of the dependency graph. Could you also publish this on crates.io? Thanks.

**Comment by SimonSapin** [comment]
One test fails on beta and nigthly: https://github.com/steveklabnik/semver/issues/105

**Comment by steveklabnik** [comment]
https://github.com/Kimundi/rustc-version-rs/pull/8 has the same problem, but is actually updating to the newest version, which is what I'd prefer.

**Comment by steveklabnik** [comment]
(As semver approaches a 1.0 I'd also like to move everyone to similar versions so as not to cause these kinds of duplication.)

**Comment by SimonSapin** [comment]
Closing for #8.

**Pull request closed without merging**
